### ISSUE TITLE
If curl is not installed on your machine.

### ISSUE THREAD

**Issue by monavariyas** [neerajkr17/Podman#4]
What is the need to use curl?

**Comment by neerajkr17** [comment]
curl is a command-line tool and library for making HTTP requests and working with URLs. It stands for "Client for URLs" or "cURL" (pronounced as "curl"). It is a versatile tool used for a variety of purposes in the context of web development, system administration, and network-related tasks. Here are some common use cases for using curl:


If curl is not install in our machine then we can't fetch the GPG key from the OpenSUSE repository, and the subsequent commands process and save this key as a keyring file for use in verifying the authenticity of packages from the repository.
