### ISSUE TITLE
If you're not able to search any image then run this command.

### ISSUE THREAD

**Issue by monavariyas** [neerajkr17/Podman#5]
- What is the difference between image and a container?

**Comment by neerajkr17** [comment]
**Image:**

An image is a lightweight, standalone, and executable software package that includes everything needed to run a piece of software, including the code, runtime, libraries, and system tools.
It is essentially a snapshot of a file system with application code and all its dependencies.
Images are read-only and provide a consistent environment for running applications, regardless of the underlying host system.
Images are typically created from a set of instructions called a Dockerfile or similar configuration files, which specify how to build the image.


**Container:**

A container is an instance of a running image. It is a lightweight and portable executable unit that includes both the application and its dependencies.
Containers run in isolated user spaces on a host system, sharing the host's kernel but with their own file systems, processes, and network interfaces.
Containers can be started, stopped, moved, and deleted easily, making them highly portable and scalable.
Containers provide a consistent and reproducible environment for applications, ensuring that they behave the same way across different environments.
