### ISSUE TITLE
To Search for a image in registry

### ISSUE THREAD

**Issue by monavariyas** [neerajkr17/Podman#6]
-What is registry?

-There is no output for command :  Podman search nginx

-What is nginx?

-To Search for a image in registry  : make small s (Search)

**Comment by neerajkr17** [comment]
1.  The term "registry" typically refers to a container image registry. A container registry is a service that stores and manages container images, which are used as the basis for creating containers. Container images contain an application or a service along with its dependencies and can be easily deployed as containers.

Podman is a container management tool that allows you to create, manage, and run containers on Linux systems. When you use Podman to run a container, it needs to pull the container image from a registry if the image is not already available locally.

Common container image registries include Docker Hub, Quay.io, Google Container Registry, and others. Podman can interact with these registries to pull, push, and manage container images.

2.  Podman search nginx : - This command give the image form registry

3. NGINX (pronounced "engine-x") is a popular open-source web server, reverse proxy server, and load balancer. It is known for its high performance, stability, and scalability, making it widely used for serving web content, managing application traffic, and improving the performance and reliability of websites.
4. Okay Ma'am
