### ISSUE TITLE
Port Binding of container

### ISSUE THREAD

**Issue by monavariyas** [neerajkr17/Podman#8]
What is Port Binding of container? Please explain it.

**Comment by neerajkr17** [comment]
In the context of containerization, port binding refers to the process of mapping network ports between the host system and the container. This allows external traffic to reach the containerized application or service running inside the container.

podman run -dt -p 8080:80/tcp docker.io/library/nginx


Here's what each part of the command does:

podman run: This is the command to run a container.

-dt: These are options specifying that the container should be run in detached mode (-d), which means it runs in the background, and in interactive mode (-t), which allocates a pseudo-TTY.

-p 8080:80/tcp: This is the port binding part. It maps port 8080 on the host to port 80 inside the container. The format is hostPort:containerPort/protocol, where hostPort is the port on the host machine, containerPort is the port inside the container, and protocol is the network protocol (in this case, TCP). This means that traffic sent to port 8080 on the host will be forwarded to port 80 inside the running Nginx container.

docker.io/library/nginx: This is the name of the Docker image used to create the container. In this case, it's the official Nginx image from the Docker Hub registry.

So, when you run this command, it starts a detached and interactive Nginx container, and it binds port 8080 on the host to port 80 inside the container. This allows you to access the Nginx web server inside the container through http://localhost:8080 on the host machine. The mapping of ports facilitates communication between the containerized application and the external network.
