### ISSUE TITLE
Installation and setup

### ISSUE THREAD

**Issue by monavariyas** [neerajkr17/Podman#9]
What we require for set up and installation of Podman?

**Comment by neerajkr17** [comment]
To set up and install Podman, you'll need to ensure that your system meets certain requirements and follow the appropriate steps based on your operating system. Here are general guidelines, but keep in mind that specifics may vary based on your Linux distribution.

System Requirements:

Operating System:
Podman is primarily designed for Linux systems, and it works best on distributions that use systemd for process management. Some common distributions include Fedora, CentOS, RHEL, Debian, and Ubuntu.

Kernel Version:
Ensure that your Linux kernel version is 3.10 or later, as Podman relies on certain features that may not be present in older kernels.
